baseURL = '/'
languageCode = 'en-us'
title = 'Lambung Mangkurat Debate Society'
theme = "spectral"

[params]
fancyTitle = "Lambung Mangkurat<br> Debate Society " # title for frontpage, may include image
img = "img/logo.png"
copyright = "LMDS"
description = '<i>Corgito Ergo Sum</i>'
startbuttonText = "About us"
startbuttonLink = "/posts/about"
body_is_markdown = true
#custom_css = "foo.css"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[[params.menu.main]]
url = '/division'
title = "Divisions"

[[params.menu.main]]
url = '/posts/about'
title = "About us"

[[params.menu.main]]
url = '/contact'
title = "Contact us"


[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'What is <br>Lambung Mangkurat Debate Society?'
body = '''
Lambung Mangkurat Debate Society is a part of the Lambung Mangkurat
University's organization that specialized in improving personal knowledge
through debating.
'''

[[params.one.icon]]
icon = "fa-users"
style = "1"
label = "Lorem"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'What is <br />debating?'
body = 'Eiusmod veniam minim occaecat elit. Est minim tempor ea veniam magna labore incididunt velit sunt esse culpa. Ut deserunt velit labore commodo commodo id qui nulla veniam irure. Sint anim velit proident laboris esse deserunt laborum tempor ea id et. Elit amet dolor ea nisi. Tempor consectetur cillum Lorem duis non ipsum labore tempor ex ea occaecat esse labore. Amet do ipsum reprehenderit occaecat incididunt sint duis fugiat irure dolore duis consectetur proident.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Why We focus on <br />personal growth through debating'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Activites in <br> Lambung Mangkurat Debate Society'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
title = "Intensive Training"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
title = "Competition"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
title = "Monthly Gathering"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
title = "Bootcamp"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."



[params.cta]
enable = true
title = "Have a question? <br> Check out our FaQ first â†’"
body = "Here you can find lists of Frequently Asked Question"

[[params.cta.link]]
href = "#"
text = "FAq"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "2110117120016@mhs.ulm.ac.id"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = "lmds_ulm"
dribble = ""